### ISSUE TITLE
Error when codegen PIR for GDA

### ISSUE THREAD

**Issue by blackwings-01** [stanford-ppl/spatial#39]
```
Exception in thread "main" java.lang.Exception: No register defined for Sym(4136)
        at spatial.compiler.ops.PIRCommon$CUContext$$anonfun$reg$1.apply(PIRCommon.scala:73)
        at spatial.compiler.ops.PIRCommon$CUContext$$anonfun$reg$1.apply(PIRCommon.scala:73)
        at scala.Option.getOrElse(Option.scala:120)
        at spatial.compiler.ops.PIRCommon$CUContext.reg(PIRCommon.scala:73)
        at spatial.compiler.ops.PIRScheduler$$anonfun$opStageToStage$3$$anonfun$8.apply(PIRScheduler.scala:312)
        at spatial.compiler.ops.PIRScheduler$$anonfun$opStageToStage$3$$anonfun$8.apply(PIRScheduler.scala:312)
        at scala.collection.immutable.List.map(List.scala:276)
```

**Comment by blackwings-01** [comment]
Similar issue for OuterProduct. Do I need to change parameters or app before running codegen?

**Comment by dkoeplin** [comment]
Was a small issue when identifying readers of input arguments. Resolved on transform branch.
